export const terms = [
  {
    name: "Ajio",
    link: "https://www.ajio.com",
    logo: "ajio-logo.png",
    count: 0,
  },
  {
    name: "Amazon",
    link: "https://www.amazon.in",
    logo: "amazon-logo.png",
    count: 0,
  },
  {
    name: "Ask Senior",
    link: "https://asksenior.in",
    logo: "asksenior-logo.png",
    count: 0,
  },
  {
    name: "Behance",
    link: "https://www.behance.net",
    logo: "behance-logo.png",
    count: 0,
  },
  {
    name: "Canva",
    link: "https://www.canva.com",
    logo: "canva-logo.png",
    count: 0,
  },
  {
    name: "ChatGPT",
    link: "https://chatgpt.com",
    logo: "chatgpt-logo.png",
    count: 0,
  },
  {
    name: "Codeforces",
    link: "https://codeforces.com",
    logo: "codeforces-logo.png",
    count: 0,
  },
  {
    name: "Coolors",
    link: "https://coolors.co",
    logo: "coolors-logo.png",
    count: 0,
  },
  {
    name: "Cosmos",
    link: "https://www.cosmos.so",
    logo: "cosmos-logo.png",
    count: 0,
  },
  {
    name: "Fitgirl Repacks",
    link: "https://fitgirl-repacks.site",
    logo: "fitgirl-logo.png",
    count: 0,
  },
  {
    name: "Flipkart",
    link: "https://www.flipkart.com",
    logo: "flipkart-logo.png",
    count: 0,
  },
  { name: "FMHY", link: "https://fmhy.net", logo: "fmhy-logo.png", count: 0 },
  {
    name: "Gemini",
    link: "https://gemini.google.com",
    logo: "gemini-logo.png",
    count: 0,
  },
  {
    name: "GitHub",
    link: "https://github.com",
    logo: "github-logo.png",
    count: 0,
  },
  {
    name: "Gmail",
    link: "https://mail.google.com",
    logo: "gmail-logo.png",
    count: 0,
  },
  {
    name: "Godly",
    link: "https://godly.website",
    logo: "godly-logo.png",
    count: 0,
  },
  {
    name: "Google Calendar",
    link: "https://calendar.google.com",
    logo: "calendar-logo.png",
    count: 0,
  },
  {
    name: "Google Docs",
    link: "https://docs.google.com",
    logo: "docs-logo.png",
    count: 0,
  },
  {
    name: "Google Drive",
    link: "https://drive.google.com",
    logo: "drive-logo.png",
    count: 0,
  },
  {
    name: "Google Fonts",
    link: "https://fonts.google.com",
    logo: "fonts-logo.png",
    count: 0,
  },
  {
    name: "Google Keep",
    link: "https://keep.google.com",
    logo: "keep-logo.png",
    count: 0,
  },
  {
    name: "HackerRank",
    link: "https://www.hackerrank.com",
    logo: "hackerrank-logo.png",
    count: 0,
  },
  {
    name: "Instagram",
    link: "https://www.instagram.com",
    logo: "instagram-logo.png",
    count: 0,
  },
  {
    name: "LinkedIn",
    link: "https://www.linkedin.com",
    logo: "linkedin-logo.png",
    count: 0,
  },
  {
    name: "Monochrome Samidy",
    link: "https://monochrome.samidy.com",
    logo: "monochrome-logo.png",
    count: 0,
  },
  {
    name: "Myntra",
    link: "https://www.myntra.com",
    logo: "myntra-logo.png",
    count: 0,
  },
  {
    name: "Pinterest",
    link: "https://www.pinterest.com",
    logo: "pinterest-logo.png",
    count: 0,
  },
  {
    name: "React Bits",
    link: "https://www.reactbits.dev",
    logo: "reactbits-logo.png",
    count: 0,
  },
  {
    name: "Reddit",
    link: "https://www.reddit.com",
    logo: "reddit-logo.png",
    count: 0,
  },
  {
    name: "Sketchfab",
    link: "https://sketchfab.com",
    logo: "sketchfab-logo.png",
    count: 0,
  },
  {
    name: "Spotify",
    link: "https://open.spotify.com",
    logo: "spotify-logo.png",
    count: 0,
  },
  {
    name: "Tailwind CSS",
    link: "https://tailwindcss.com",
    logo: "tailwind-logo.png",
    count: 0,
  },
  {
    name: "Telegram Web",
    link: "https://web.telegram.org",
    logo: "telegram-logo.png",
    count: 0,
  },
  {
    name: "The Odin Project",
    link: "https://www.theodinproject.com",
    logo: "odin-logo.png",
    count: 0,
  },
  {
    name: "Twitch",
    link: "https://www.twitch.tv",
    logo: "twitch-logo.png",
    count: 0,
  },
  { name: "Twitter", link: "https://x.com", logo: "x-logo.png", count: 0 },
  {
    name: "YouTube",
    link: "https://www.youtube.com",
    logo: "youtube-logo.png",
    count: 0,
  },
];
