export const terms = [
  {
    name: "Ajio",
    link: "https://www.ajio.com",
    logo: "ajioLogo.png",
    count: 0,
  },
  {
    name: "Amazon",
    link: "https://www.amazon.in",
    logo: "amazonLogo.png",
    count: 0,
  },
  {
    name: "Ask Senior",
    link: "https://asksenior.in",
    logo: "askseniorLogo.png",
    count: 0,
  },
  {
    name: "Behance",
    link: "https://www.behance.net",
    logo: "behanceLogo.png",
    count: 0,
  },
  {
    name: "Canva",
    link: "https://www.canva.com",
    logo: "canvaLogo.png",
    count: 0,
  },
  {
    name: "ChatGPT",
    link: "https://chatgpt.com",
    logo: "chatgptLogo.png",
    count: 0,
  },
  {
    name: "Codeforces",
    link: "https://codeforces.com",
    logo: "codeforcesLogo.png",
    count: 0,
  },
  {
    name: "Coolors",
    link: "https://coolors.co",
    logo: "coolorsLogo.png",
    count: 0,
  },
  {
    name: "Cosmos",
    link: "https://www.cosmos.so",
    logo: "cosmosLogo.png",
    count: 0,
  },
  {
    name: "Fitgirl Repacks",
    link: "https://fitgirl-repacks.site",
    logo: "fitgirlLogo.png",
    count: 0,
  },
  {
    name: "Flipkart",
    link: "https://www.flipkart.com",
    logo: "flipkartLogo.png",
    count: 0,
  },
  { name: "FMHY", link: "https://fmhy.net", logo: "fmhyLogo.png", count: 0 },
  {
    name: "Gemini",
    link: "https://gemini.google.com",
    logo: "geminiLogo.png",
    count: 0,
  },
  {
    name: "GitHub",
    link: "https://github.com",
    logo: "githubLogo.png",
    count: 0,
  },
  {
    name: "Gmail",
    link: "https://mail.google.com",
    logo: "gmailLogo.png",
    count: 0,
  },
  {
    name: "Godly",
    link: "https://godly.website",
    logo: "godlyLogo.png",
    count: 0,
  },
  {
    name: "Google Calendar",
    link: "https://calendar.google.com",
    logo: "calendarLogo.png",
    count: 0,
  },
  {
    name: "Google Docs",
    link: "https://docs.google.com",
    logo: "docsLogo.png",
    count: 0,
  },
  {
    name: "Google Drive",
    link: "https://drive.google.com",
    logo: "driveLogo.png",
    count: 0,
  },
  {
    name: "Google Fonts",
    link: "https://fonts.google.com",
    logo: "fontsLogo.png",
    count: 0,
  },
  {
    name: "Google Keep",
    link: "https://keep.google.com",
    logo: "keepLogo.png",
    count: 0,
  },
  {
    name: "HackerRank",
    link: "https://www.hackerrank.com",
    logo: "hackerrankLogo.png",
    count: 0,
  },
  {
    name: "Instagram",
    link: "https://www.instagram.com",
    logo: "instagramLogo.png",
    count: 0,
  },
  {
    name: "LinkedIn",
    link: "https://www.linkedin.com",
    logo: "linkedinLogo.png",
    count: 0,
  },
  {
    name: "Monochrome",
    link: "https://monochrome.samidy.com",
    logo: "monochromeLogo.png",
    count: 0,
  },
  {
    name: "Myntra",
    link: "https://www.myntra.com",
    logo: "myntraLogo.png",
    count: 0,
  },
  {
    name: "Pinterest",
    link: "https://www.pinterest.com",
    logo: "pinterestLogo.png",
    count: 0,
  },
  {
    name: "React Bits",
    link: "https://www.reactbits.dev",
    logo: "reactbitsLogo.png",
    count: 0,
  },
  {
    name: "Reddit",
    link: "https://www.reddit.com",
    logo: "redditLogo.png",
    count: 0,
  },
  {
    name: "Sketchfab",
    link: "https://sketchfab.com",
    logo: "sketchfabLogo.png",
    count: 0,
  },
  {
    name: "Spotify",
    link: "https://open.spotify.com",
    logo: "spotifyLogo.png",
    count: 0,
  },
  {
    name: "Tailwind CSS",
    link: "https://tailwindcss.com",
    logo: "tailwindLogo.png",
    count: 0,
  },
  {
    name: "Telegram Web",
    link: "https://web.telegram.org",
    logo: "telegramLogo.png",
    count: 0,
  },
  {
    name: "The Odin Project",
    link: "https://www.theodinproject.com",
    logo: "odinLogo.png",
    count: 0,
  },
  {
    name: "Twitch",
    link: "https://www.twitch.tv",
    logo: "twitchLogo.png",
    count: 0,
  },
  { name: "Twitter", link: "https://x.com", logo: "xLogo.png", count: 0 },
  {
    name: "YouTube",
    link: "https://www.youtube.com",
    logo: "youtubeLogo.png",
    count: 0,
  },
  {
    name: "Search Google",
    link: "https://www.google.com/search?q=",
    logo: "googleSearchLogo.png",
  },
  {
    name: "Scientific Calculator",
    link: "https://www.desmos.com/scientific",
    logo: "desmosLogo.png"
  },
  {
    name: "Overleaf [Latex]",
    link: "https://www.overleaf.com/project",
    logo: "overleafLogo.png"
  }
];